export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'

export const USER_LOGOUT = 'USER_LOGOUT'

export const GET_BATCHES = 'GET_BATCHES'
export const BATCH_SUCCESS = 'BATCH_SUCCESS'
export const BATCH_FAILED = 'BATCH_FAILED'

export const GET_STUDENTS = 'GET_STUDENTS'
export const STUDENT_SUCCESS = 'STUDENTS_SUCCESS'
export const STUDENT_FAIL = 'STUDENTS_FAIL'

export const GET_EVALUATIONS = 'GET_EVALUATIONS'
export const ADD_EVALUATION_SUCCESS = 'ADD_EVALUATION_SUCCESS'
export const ADD_EVALUATION_FAIL = 'ADD_EVALUATION_FAIL'
